[package]
name = "dann-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dann = { git = "https://github.com/victor-savu/dann", branch = "prop" }
plotly = "0.8.3"
itertools-num = "0.1.3"